services:
  # Web Service
  - type: web
    name: tyaira-driving-test
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tyaira-db
          property: connectionString
    autoDeploy: true

  # PostgreSQL Database
  - type: postgres
    name: tyaira-db
    region: oregon
    plan: free
    databaseName: tyaira
    databaseUser: tyaira_user
    ipAllowList: []
